from .visiontek_rgb_loader import Visiontek_rgb_loader
from .visiontek_rgbi_loader import Visiontek_rgbi_loader
from .GID_dataloader import GID_rgb_dataset
from .deepglobe_rgb_loader import Deepglobe_rgb_loader